### ISSUE TITLE
Problems with compiling binary which uses FFI

### ISSUE THREAD

**Issue by josemanimala** [vijaymathew/slogan#3]
../test.sn.scm:
/home/vagrant/test.sn.c:
/home/vagrant/test.sn_.c:
slogan/src/prelude/libffi.slgn.o: In function `slogan_obj_to_c_struct':
libffi.slgn.c:(.text+0x133): undefined reference to`ffi_type_sint8'
libffi.slgn.c:(.text+0x171): undefined reference to `ffi_type_sint16'
libffi.slgn.c:(.text+0x1a5): undefined reference to`ffi_type_sint32'
libffi.slgn.c:(.text+0x1d7): undefined reference to `ffi_type_uint8'
libffi.slgn.c:(.text+0x20a): undefined reference to`ffi_type_uint16'
libffi.slgn.c:(.text+0x23e): undefined reference to `ffi_type_uint32'
libffi.slgn.c:(.text+0x270): undefined reference to`ffi_type_sint64'
libffi.slgn.c:(.text+0x2a4): undefined reference to `ffi_type_uint64'
libffi.slgn.c:(.text+0x2d8): undefined reference to`ffi_type_float'
libffi.slgn.c:(.text+0x30a): undefined reference to `ffi_type_double'
libffi.slgn.c:(.text+0x33e): undefined reference to`ffi_type_longdouble'
libffi.slgn.c:(.text+0x3b2): undefined reference to `ffi_type_pointer'
slogan/src/prelude/libffi.slgn.o: In function`c_struct_to_slogan_obj_':
libffi.slgn.c:(.text+0x559): undefined reference to `ffi_type_sint16'
libffi.slgn.c:(.text+0x563): undefined reference to`ffi_type_sint8'
libffi.slgn.c:(.text+0x56e): undefined reference to `ffi_type_sint32'
libffi.slgn.c:(.text+0x5ca): undefined reference to`ffi_type_uint8'
libffi.slgn.c:(.text+0x5d6): undefined reference to `ffi_type_uint16'
libffi.slgn.c:(.text+0x5e6): undefined reference to`ffi_type_uint32'
libffi.slgn.c:(.text+0x64a): undefined reference to `ffi_type_sint64'
libffi.slgn.c:(.text+0x67a): undefined reference to`ffi_type_uint64'
libffi.slgn.c:(.text+0x6aa): undefined reference to `ffi_type_float'
libffi.slgn.c:(.text+0x6db): undefined reference to`ffi_type_double'
libffi.slgn.c:(.text+0x70c): undefined reference to `ffi_type_longdouble'
libffi.slgn.c:(.text+0x775): undefined reference to`ffi_type_pointer'
slogan/src/prelude/libffi.slgn.o: In function `libffi_fncall':
libffi.slgn.c:(.text+0xa60): undefined reference to`ffi_type_sint32'
libffi.slgn.c:(.text+0xa6f): undefined reference to `ffi_type_sint8'
libffi.slgn.c:(.text+0xa7e): undefined reference to`ffi_type_sint16'
libffi.slgn.c:(.text+0xacd): undefined reference to `ffi_type_uint8'
libffi.slgn.c:(.text+0xad8): undefined reference to`ffi_type_uint32'
libffi.slgn.c:(.text+0xae7): undefined reference to `ffi_type_uint16'
libffi.slgn.c:(.text+0xb36): undefined reference to`ffi_type_sint64'
libffi.slgn.c:(.text+0xb89): undefined reference to `ffi_type_uint64'
libffi.slgn.c:(.text+0xbde): undefined reference to`ffi_type_float'
libffi.slgn.c:(.text+0xc2d): undefined reference to `ffi_type_double'
libffi.slgn.c:(.text+0xc7c): undefined reference to`ffi_type_longdouble'
libffi.slgn.c:(.text+0xcdd): undefined reference to `ffi_type_pointer'
libffi.slgn.c:(.text+0xe06): undefined reference to`ffi_prep_cif'
libffi.slgn.c:(.text+0xe55): undefined reference to `ffi_call'
libffi.slgn.c:(.text+0xe8a): undefined reference to`ffi_call'
libffi.slgn.c:(.text+0xed0): undefined reference to `ffi_call'
libffi.slgn.c:(.text+0xf17): undefined reference to`ffi_call'
libffi.slgn.c:(.text+0xf5e): undefined reference to `ffi_call'
slogan/src/prelude/libffi.slgn.o:libffi.slgn.c:(.text+0xfa5): more undefined references to`ffi_call' follow
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x0): undefined reference to `ffi_type_uint8'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x8): undefined reference to`ffi_type_sint8'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x10): undefined reference to `ffi_type_uint16'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x18): undefined reference to`ffi_type_sint16'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x20): undefined reference to `ffi_type_uint32'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x28): undefined reference to`ffi_type_sint32'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x30): undefined reference to `ffi_type_uint8'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x38): undefined reference to`ffi_type_sint8'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x40): undefined reference to `ffi_type_uint16'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x48): undefined reference to`ffi_type_sint16'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x50): undefined reference to `ffi_type_uint32'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x58): undefined reference to`ffi_type_sint32'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x60): undefined reference to `ffi_type_uint64'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x68): undefined reference to`ffi_type_sint64'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x70): undefined reference to `ffi_type_uint64'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x78): undefined reference to`ffi_type_sint64'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x80): undefined reference to `ffi_type_float'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x88): undefined reference to`ffi_type_double'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0x90): undefined reference to `ffi_type_longdouble'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0xa0): undefined reference to`ffi_type_pointer'
slogan/src/prelude/libffi.slgn.o:(.data.rel.ro+0xa8): undefined reference to `ffi_type_void'
collect2: error: ld returned 1 exit status
**\* ERROR IN ##main -- C link failed while linking "/home/vagrant/slogan/src/prelude/array.slgn.o" "/home/vagrant/slogan/src/prelude/bitvect.slgn.o" "/home/vagrant/slogan/src/prelude/char.slgn.o" "/home/vagrant/slogan/src/prelude/compiler.slgn.o" "/home/vagrant/slogan/src/prelude/consts.slgn.o" "/home/vagrant/slogan/src/prelude/extn.slgn.o" "/home/vagrant/slogan/src/prelude/ffi.slgn.o" "/home/vagrant/slogan/src/prelude/libffi.slgn.o" "/home/vagrant/slogan/src/prelude/list.slgn.o" "/home/vagrant/slogan/src/prelude/macro_lazy.slgn.o" "/home/vagrant/slogan/src/prelude/match.slgn.o" "/home/vagrant/slogan/src/prelude/namespace.slgn.o" "/home/vagrant/slogan/src/prelude/number.slgn.o" "/home/vagrant/slogan/src/prelude/os.slgn.o" "/home/vagrant/slogan/src/prelude/parser.slgn.o" "/home/vagrant/slogan/src/prelude/ports.slgn.o" "/home/vagrant/slogan/src/prelude/stream.slgn.o" "/home/vagrant/slogan/src/prelude/string.slgn.o" "/home/vagrant/slogan/src/prelude/table.slgn.o" "/home/vagrant/slogan/src/prelude/task.slgn.o" "/home/vagrant/slogan/src/prelude/time.slgn.o" "/home/vagrant/slogan/src/prelude/tokenizer.slgn.o" "/home/vagrant/slogan/src/prelude/util.slgn.o" "/home/vagrant/test.sn.o" "/home/vagrant/test.sn_.o"
vagrant@vagrant:~/slogan$ ./src/slogan -x ../test.sn

**Comment by vmatp** [comment]
This fix also makes sure that the `SLOGAN_ROOT` environment variable is available to the Slogan interpreter if it is installed system-wide via `make install`.
